services:
  db:
    image: postgres:17-alpine
    container_name: wildx-db
    environment:
      POSTGRES_USER: wildx
      POSTGRES_PASSWORD: wildx
      POSTGRES_DB: wildx
    ports:
      - "5432:5432"
    volumes:
      - wildx-db:/var/lib/postgresql/data

volumes:
  wildx-db:
